name: Create Archive
on: 
  push:
    branches:
    - main

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          filename: "release.zip"
          exclusions: "*.git* /*node_modules/* .editorconfig *.md"
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          release_name: "Version <RELEASE_VERSION>"
